services:
  clipper:
    build:
      context: .
    ports:
      - "8002:8000"
    volumes:
      - ./media:/code/media
    depends_on:
      - postgres
      - minik

  postgres:
    image: postgres:18.1-bookworm
    restart: always
    environment:
      - POSTGRES_DB=clipper
      - POSTGRES_USER=clipper
      - POSTGRES_PASSWORD=clipper
    ports:
      - "5432:5432"

  minik:
    image: quay.io/minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
    volumes:
      - ./media:/data
    
    # needed for keeping the server running and serving
    command: server /data --console-address ":9001"
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-monitoring
    ports:
      - 8001:9090
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml