services:
  clipper:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./media:/code/media
    depends_on:
      - postgres

  postgres:
    image: postgres:18.1-bookworm
    restart: always
    environment:
      - POSTGRES_DB=clipper
      - POSTGRES_USER=clipper
      - POSTGRES_PASSWORD=clipper
    ports:
      - "5432:5432"